### ISSUE TITLE
Not working with AdGuard on cellular network

### ISSUE THREAD

**Issue by jay-0625** [AdguardTeam/AdGuardVPNForiOS#182]
It couldn't be worked with AdGuard(paid lifetime license) with cellular network by iPhone 12 Pro Max, iPhone 14 Pro Max, and iPad Pro 12.9 inch 5th generation. those devices runs iOS 16 or iPadOS 16. all of that devices runs both at same time only when connected with wifi network. It happenes only when on cellular network. for addition, it happened on SKTelecom and KT, which mobile carriers in South Korea

**Comment by mozartinio** [comment]
@jay-0625 Hello! Can you please sent us your logs
Here's what we need you to do:

Open Settings --> General --> Turn Advanced mode on --> Advanced settings --> Turn Debug logs switch on;
Reproduce the issue and remember the exact time when it happened (Connect to your WIFI and then your cellular network)
Disable "DNS Privacy";
Open the settings --> Support --> Export logs;
System popup will be opened --> Choose "Mail" app
Enter apple@adguard.com as a recipient;
Mention this issue number in the subject and add the time the issue was reproduced at.

**Comment by mozartinio** [comment]
@jay-0625 Any news?

**Comment by mozartinio** [comment]
@jay-0625 I'm closing the issue. If your problem still persist just reopen it please
